spring.application.name=moeats
spring.profiles.active=dev
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html 

 
spring.datasource.username=root
spring.datasource.password=1234

spring.thymeleaf.cache=false

mybatis.mapper-locations=classpath:/mappers/**/*.xml
mybatis.type-aliases-package=com.moeats
mybatis.configuration.map-underscore-to-camel-case=true

spring.main.allow-bean-definition-overriding=true
server.port=9090
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true