spring.application.name=moeats
spring.profiles.active=dev

spring.thymeleaf.cache=false

mybatis.mapper-locations=classpath:/mappers/**/*.xml
mybatis.type-aliases-package=com.moeats
mybatis.configuration.map-underscore-to-camel-case=true

server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

