spring.application.name=moeats
spring.profiles.active=dev

spring.thymeleaf.cache=false

mybatis.mapper-locations=classpath:/mappers/**/*.xml
mybatis.type-aliases-package=com.moeats.domain
mybatis.configuration.map-underscore-to-camel-case=true

server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

kakao.api-key=KakaoAK 8656012ca59f9bc533802e21e456f628